# Generated by Django 6.1.1 on 2026-09-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('half_wife', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('dish_image', models.ImageField(upload_to='media/')),
                ('description', models.TextField()),
            ],
        ),
    ]
