# Generated by Django 6.1.1 on 2026-09-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('half_wife', '0002_menumanagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='menumanagement',
            name='status',
            field=models.CharField(default='Available', max_length=20),
        ),
        migrations.AddField(
            model_name='menumanagement',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
