# Generated by Django 6.1.1 on 2026-09-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('half_wife', '0003_menumanagement_status_menumanagement_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='hireEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('emp_role', models.CharField(max_length=100)),
                ('emp_salary', models.IntegerField()),
                ('emp_email', models.EmailField(max_length=254)),
                ('emp_password', models.CharField(max_length=100)),
                ('emp_duty_status', models.CharField(default='On Duty', max_length=20)),
            ],
        ),
    ]
