# Generated by Django 6.1.1 on 2026-09-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('half_wife', '0004_hireemployee'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorAndTables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=100)),
                ('seating_capacity', models.IntegerField()),
                ('zone_area', models.CharField(max_length=200)),
            ],
        ),
    ]
