# Generated by Django 6.1.1 on 2026-09-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('half_wife', '0008_alter_hireemployee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='order_items',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
