# Generated by Django 6.1.1 on 2026-09-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('half_wife', '0009_checkout_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
