# Generated by Django 6.1.1 on 2026-09-21 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('half_wife', '0011_checkout_is_supplemental'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='fulfillment_type',
            field=models.CharField(default='Delivery', max_length=100),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_status', models.CharField(choices=[('packed', 'Packed'), ('picked up', 'Picked Up'), ('on the way', 'On The Way'), ('delivered', 'Delivered')], default='packed', max_length=30)),
                ('est_time', models.CharField(default='15 mins', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='half_wife.hireemployee')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='half_wife.checkout')),
            ],
        ),
    ]
