# Generated by Django 6.1.1 on 2026-09-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('half_wife', '0012_checkout_delivery_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_status',
            field=models.CharField(choices=[('packed', 'Packed'), ('picked-up', 'Picked Up'), ('on-the-way', 'On The Way'), ('delivered', 'Delivered')], default='packed', max_length=30),
        ),
    ]
