# Generated by Django 6.1.1 on 2026-09-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('half_wife', '0013_alter_delivery_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumanagement',
            name='dish_image',
            field=models.ImageField(blank=True, null=True, upload_to='dishes/'),
        ),
    ]
